[metadata]
name = docker-compose-py
version = 5.6.0.0
description = Python wrapper around invoking the Docker Compose CLI (https://github.com/docker/compose)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/neeve-ai/docker-compose-py
author = oss-robin
license = Apache License Version 2.0
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy

[options]
python_requires = >=3.11
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [docker-compose]
    group = docker-compose-binary
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/docker/compose/releases/download/v5.6.0/docker-compose-linux-x86_64
    sha256 = 40343e21ca777173e69cff5dbafeb37c6f81f3b0d57d9e597f036e95eb63e76a
    [docker-compose]
    group = docker-compose-binary
    marker = sys_platform == "linux" and platform_machine == "aarch64"
    url = https://github.com/docker/compose/releases/download/v5.6.0/docker-compose-linux-aarch64
    sha256 = 733ec76717ceb59052a9609b9dadfb523b2df8eab57a54212872d10a58078ea2
    [docker-compose]
    group = docker-compose-binary
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    url = https://github.com/docker/compose/releases/download/v5.6.0/docker-compose-darwin-x86_64
    sha256 = c76e3abf5fde1aeb3bd7c7306ff15bef2246afc1f9e54832a0a050dd7cdfb2f8
    [docker-compose]
    group = docker-compose-binary
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/docker/compose/releases/download/v5.6.0/docker-compose-darwin-aarch64
    sha256 = bd714a42b46e51757fc1121085b3096b9064e3f80d3ca5a991e33f44df4f43c9
    [docker-compose.exe]
    group = docker-compose-binary
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    url = https://github.com/docker/compose/releases/download/v5.6.0/docker-compose-windows-x86_64.exe
    sha256 = 8aeaa0055e660e12cf07cd70680dc8333957fe6718528b91ec3da084eab62483
    [docker-compose.exe]
    group = docker-compose-binary
    marker = sys_platform == "win32" and platform_machine == "ARM64"
    url = https://github.com/docker/compose/releases/download/v5.6.0/docker-compose-windows-aarch64.exe
    sha256 = 73cdc73a03443cba37c7ae91aec12c7b86c0eb75a8f40f296aaa5159e66b29bc
